# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Exponential (scalar implementation)
#'
#' @param t time
#' @param A rate matrix
#'
#' @return probability matrix
#' @export
ExpMat_C <- function(t, A) {
    .Call('_PhenoTraits_ExpMat_C', PACKAGE = 'PhenoTraits', t, A)
}

#' Matrix Exponential (vector implementation)
#'
vExpMat_C <- function(t, Q) {
    .Call('_PhenoTraits_vExpMat_C', PACKAGE = 'PhenoTraits', t, Q)
}

Exp_2Q_C <- function(t1, t2, Tau, Q1, Q2) {
    .Call('_PhenoTraits_Exp_2Q_C', PACKAGE = 'PhenoTraits', t1, t2, Tau, Q1, Q2)
}

vExp_2Q_t1_C <- function(t1, t2, Tau, Q1, Q2) {
    .Call('_PhenoTraits_vExp_2Q_t1_C', PACKAGE = 'PhenoTraits', t1, t2, Tau, Q1, Q2)
}

Exp_2Q_scen3_C <- function(t1, Tau, Q1, Q2) {
    .Call('_PhenoTraits_Exp_2Q_scen3_C', PACKAGE = 'PhenoTraits', t1, Tau, Q1, Q2)
}

vExp_2Q_scen3_C <- function(t1, Tau, Q1, Q2) {
    .Call('_PhenoTraits_vExp_2Q_scen3_C', PACKAGE = 'PhenoTraits', t1, Tau, Q1, Q2)
}

